data:
  train_dir: "multimodal-data/welding_dataset/images/train"
  train_ann: "multimodal-data/welding_dataset/train_annotations.csv"
  val_dir: "multimodal-data/welding_dataset/images/val"
  val_ann: "multimodal-data/welding_dataset/val_annotations.csv"
  batch_size: 4
  num_workers: 8
  negative_sampling_rate: 1.0

model:
  config_path: "groundingdino/config/GroundingDINO_SwinT_OGC.py"
  weights_path: "weights/groundingdino_swint_ogc.pth"

training:
  num_epochs: 200
  learning_rate: 1e-3
  save_dir: "weights"
  save_frequency: 5
  warmup_epochs: 5
  use_lora: true
  visualization_frequency: 5
  use_gradient_clipping: true
  max_grad_norm: 5.0